

services:
  php:
    build: .
    container_name: servidor-php
    ports:
      - "8000:80"
    volumes:
      - ./laravel/config/apache.conf:/etc/apache2/sites-available/000-default.conf
      - frontend-build:/var/www/html/public/build
      
    environment:
      - DB_HOST=db
    links:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'electron'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: frontend
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - frontend-build:/var/www/html/public/build
    networks:
      - app-network

volumes:
  db-data:
  frontend-build:

networks:
  app-network:
    driver: bridge