
services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./laravel/config/apache.conf:/etc/apache2/sites-available/000-default.conf
      
    environment:
      - DB_HOST=db
    links:
    - db
  db:
    image: mysql:latest  # Especifique a imagem do seu banco de dados
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'electron'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql  # Volume para persistir os dados do banco de dados

volumes:
  db-data:  

