# Set the base image
FROM node:20

# Set working directory
WORKDIR /var/www/html

# Copy `package.json` and `package-lock.json`
COPY laravel ./

# Install project dependencies
RUN npm install

# Copy project files into the docker image

# Start the Vite server
CMD ["npm", "run", "dev"]